### ISSUE TITLE
More generious Table/Column-naming options

### ISSUE THREAD

**Issue by brhrenad** [SnipeLike/WebSysLog#1]
Hi

I'm looking for a Webfrontend for an syslog-Server and I stumbled over this project. I played around a little bit and noticed that in my case the columns in the database are named differently.

I added another file dbhelper.php which handles the low-level database connections functionalities and apart from that implements a "Column Name translation table" defined in config.php.

In this translation table it's more easy to adopt WebSysLog different naming schemes.

Functionality shouldn't be altered from your latest commit!

[WebSysLog.zip](https://github.com/SnipeLike/WebSysLog/files/3085753/WebSysLog.zip)

Maybe you are interested in such functionality too, so I like to share my work with you.

BR

Bernhard

**Comment by k-304** [comment]
Hi Bernhard,
Thanks for your submission. Looks good to me so far. Would you like to create a PullRequest on this fork? So I could merge your work into the fork.
SL

**Comment by k-304** [comment]
Fixed in https://github.com/SnipeLike/WebSysLog/pull/2
